name: deploy to lambda
on:
  push:
    branches:
      - master
jobs:
  test:
    name: run tests
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node env
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run test
      env:
        CI: true
  deploy_source:
    name: deploy to lambda
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install and build
        run: |
          npm ci
          npm prune --production
        env:
          CI: true
      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -r ./app.zip board.js draw-canvas.js draw-error.js effects fonts grid.js icon.js index.js input-parser.js line.js colour.js wall.js node_modules options.js overlay.js overlays parsers renderer room.js styles.css token.js 5xx.jpg missing-token.jpg 
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-2
          s3_bucket: otfbm-deploy
          function_name: otfbm
          zip_file: app.zip